# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 23:24
from __future__ import unicode_literals

import bam_a_py.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='job_function',
            field=enumfields.fields.EnumField(enum=bam_a_py.users.models.JobFunction, max_length=3, null=True),
        ),
    ]
