# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencies_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'verbose_name_plural': 'Competencies'},
        ),
        migrations.RenameField(
            model_name='competency',
            old_name='levels',
            new_name='level',
        ),
    ]
